### ISSUE TITLE
signing JSON-LD fails

### ISSUE THREAD

**Issue by harlantwood** [WebOfTrustInfo/rebooting-the-web-of-trust-fall2016#23]
Signing some JSON-LD (represented here as a JS object) works fine, eg:

``` js
{
  '@context': {
    schema: 'http://schema.org/',
    name: 'schema:name',
    homepage: 'schema:url',
    image: 'schema:image'
  },
  name: 'Manu Sporny',
  homepage: 'https://manu.sporny.org/',
  image: 'https://manu.sporny.org/images/manu.png'
}
```

(full code [here](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/blob/debug/working-claim/draft-documents/portable-reputation/src/claim#L6-L16))

but when I try to sign this JSON-LD:

``` js
{
  "@context": "https://w3id.org/security/v1",
  "id": "http://example.gov/credentials/3732",
  "type": ["Credential", "ProofOfAgeCredential"],
  "issuer": "https://dmv.example.gov",
  "issued": "2010-01-01",
  "claim": {
    "id": "did:ebfeb1f712ebc6f1c276e12ec21",
    "ageOver": 21
  }
}
```

(full code [here](https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/blob/debug/failing-claim/draft-documents/portable-reputation/src/claim#L6-L16))

it fails with the message:

```
Error: [jsig.sign] The data to sign is empty. This error may be because a "@context" was not supplied in the input thereby causing any terms or prefixes to be undefined. Input:
{
  "@context": "https://w3id.org/security/v1",
  "id": "http://example.gov/credentials/3732",
  "type": [
    "Credential",
    "ProofOfAgeCredential"
  ],
  "issuer": "https://dmv.example.gov",
  "issued": "2010-01-01",
  "claim": {
    "id": "did:ebfeb1f712ebc6f1c276e12ec21",
    "ageOver": 21
  }
}
    at Array.async.auto.sign (/Users/harlan/code/rebooting-the-web-of-trust-fall2016/draft-documents/portable-reputation/src/node_modules/jsonld-signatures/lib/jsonld-signatures.js:202:25)
    at listener (/Users/harlan/code/rebooting-the-web-of-trust-fall2016/draft-documents/portable-reputation/src/node_modules/async/lib/async.js:605:42)
    at /Users/harlan/code/rebooting-the-web-of-trust-fall2016/draft-documents/portable-reputation/src/node_modules/async/lib/async.js:544:17
    at _arrayEach (/Users/harlan/code/rebooting-the-web-of-trust-fall2016/draft-documents/portable-reputation/src/node_modules/async/lib/async.js:85:13)
    at Immediate.taskComplete (/Users/harlan/code/rebooting-the-web-of-trust-fall2016/draft-documents/portable-reputation/src/node_modules/async/lib/async.js:543:13)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

This means that after canonicalization the message is empty. Perhaps this means that the context and this example don't match?  

Help requested: @msporny @dlongley @gwillen @TimDaub 

For full local repro:

``` sh
git clone git@github.com:WebOfTrustInfo/rebooting-the-web-of-trust-fall2016.git
cd rebooting-the-web-of-trust-fall2016/draft-documents/portable-reputation/src
git checkout debug/failing-claim    # and/or debug/working-claim
npm install
./claim
```

**Comment by dlongley** [comment]
@harlantwood,

> Perhaps this means that the context and this example don't match?

Yes, that's the case here. The context does not define the terms (e.g. "id", "type", "issuer", "issued", etc.) used in the data. Using a `@context` of `https://w3id.org/credentials/v1` would help a bit, defining everything but the `ageOver` property, I think. It's probably just a bad example that needs some tweaking.

**Comment by harlantwood** [comment]
Thanks @dlongley, much appreciated.

**Comment by harlantwood** [comment]
This fixed it, yay :)

Project update:

live claim on IPFS: https://ipfs.io/ipfs/QmW78stb69zeU55mstyu5G3mYaf3F16crTjEBYL1en9ZNA

generated by this code: https://github.com/WebOfTrustInfo/rebooting-the-web-of-trust-fall2016/blob/master/draft-documents/portable-reputation/src/claim

which:
1. generates claim
2. signs with btc key
3. timestamps with OpenTimestamps
4. uploads resulting JSON-LD to IPFS
